### ISSUE TITLE
Two issues: 1-Not possible to create mosaics for the years 2022 and 2023. 2-The display of the pdf is not working1

### ISSUE THREAD

**Issue by teopista** [openforis/clip-time-series#89]
After multiple tests, I realized that when I include the years 2022 and 2023 in the series, I get the error below

![image](https://user-images.githubusercontent.com/41087680/220614837-79eb9c1d-9471-44d2-9723-8ce4ba95015c.png)

Another issue is that the display option gives an error also seen in the image. This happens when the pdf is created and saved under module results.

**Comment by 12rambau** [comment]
I think it was hard blocked to 2022 so if you only require images in the year 2022 ther will be nothing. thanks for reporting !

**Comment by 12rambau** [comment]
landsat will not be updated on earthengine anymore. see this publication: https://gis.stackexchange.com/a/449113/154945

**Comment by eriklindquist** [comment]
Collection 1 Landsat data is deprecated.
You have to switch to Collection 2.
Collection 2 will continue to be updated as normal in GEE.

Erik Lindquist, PhD
Forestry Officer
Forestry Division
Food and Agriculture Organization of the United Nations
Rome, Italy 00153
________________________________

**Comment by 12rambau** [comment]
note that they have the very nice idea of changing all bands names ....

**Comment by teopista** [comment]
As of now, starting the tool brings a huge error with KeyError: 'refresh_token'. Please help

**Comment by 12rambau** [comment]
linked to https://github.com/openforis/sepal/issues/277 unfortunately I don't have push rights on the prod server and Daniel is on leave. 

as a workaround you can run it from your computer with the "nox -s app" command if you clone this repository.
