### ISSUE TITLE
module 'planet' has no attribute 'data'

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/clip-time-series#96]
when using planet as output:

    292 # create a title list to be consistent
    293 title_list = {
--> 294     m: {i: f"{planet.data} {mosaic_name(m)[1]}" for i in range(len(buffers))}
    295     for m in mosaics
    296 }
    298 return vrt_list, title_list

File ~/1_modules/clip-time-series/component/scripts/planet.py:294, in <dictcomp>(.0)
    290     vrt_list[m] = vrt_path
    292 # create a title list to be consistent
    293 title_list = {
--> 294     m: {i: f"{planet.data} {mosaic_name(m)[1]}" for i in range(len(buffers))}
    295     for m in mosaics
    296 }
    298 return vrt_list, title_list

AttributeError: module 'planet' has no attribute 'data'

**Comment by teopista** [comment]
I think it's the same thing I am experiencing
![image](https://github.com/sepal-contrib/clip-time-series/assets/41087680/780c3c70-cf8b-44fd-a72a-03e18c1e3a23)

**Comment by dfguerrerom** [comment]
fixed with e15916b2d18a3d6aea3739865512cb2e9c29fd7c
