### ISSUE TITLE
no "refresh token" gee

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/clip-time-series#98]
when venv is created, the earthengine-api line in requirements.txt is overwriting sepal gee-api installation, we should remove it

**Comment by 12rambau** [comment]
you should instead leave "earthengine-api" alone without any pins. To make sure it continues to work elswhere. As it's already installed in SEPAL venv it will not change version

**Comment by dfguerrerom** [comment]
that's exactly how it is on `release`, and it triggers the error.

**Comment by 12rambau** [comment]
was it updated since last week ? we changed the installation order of earthengine-api last week on prod (so anything that has not been updated since then should have badly designed venv)

**Comment by dfguerrerom** [comment]
ah okay... the latest venv update for this app was on `May 4 at 10 am`... by that moment I think SEPAL build was installing the app requirements before installing the forked version of `earthengine-api`... that's why you changed the order in https://github.com/openforis/sepal/commit/556d30b258fe27a2a47e55f7beace12c8432be4a. 
I will rebuild the venv

**Comment by dfguerrerom** [comment]
fixed with 38e348d35ad2909b0efbfb21e6ba8dc90ffe3fbd
